### ISSUE TITLE
PHP Social Share

### ISSUE THREAD

**Issue by dunglas** [neemzy/share-extension#1]
Hello,

I've released some time ago a library with similar goals: https://github.com/dunglas/php-socialshare
It supports more networks and allows to retrieve the number of share but it doesn't expose Twig helpers.

What do you think about using it internally in those extensions?

**Comment by neemzy** [comment]
Hi Kevin,

There's not much in common in those two projects AFAIK - yours focuses on retrieving a share count, with caching and all, while mine is a plain Twig extension generating HTML links for share pop-ups with ideal window sizes. I don't really see the point in weighing it up, as developers sometimes just want to expose a link without further API interaction.

Feel free to fork mine, write an adapter, or anything though - I'll be glad to give you any help.

Thanks for your interest, regards.

**Comment by dunglas** [comment]
Hi Tom,

Getting the count is an extra feature but it is also able to "only" generate the link.
What I've in mind is giving a way to generate non-JS link (with or without counts) from Twig.

**Comment by neemzy** [comment]
Well, this was a quickly-written project on my side, as you may imagine by looking at the code.

Making it rely on yours would obviously enhance it, but I'd have to rewrite it properly (like in "more than one dirty class"), version it and so on. I don't really have time to work on it these days, but be sure I'll add it to my (already too long) todolist and look into it when I get the chance.

Thanks again :) I'll leave the issue open.

**Comment by neemzy** [comment]
[I delivered](https://github.com/neemzy/share-extension/commit/7de353e479ec808b47bd4eea866a7a4f4c8ac95e). Didn't feel the need to bother with multiple classes after all, especially just for the sake of instantiation, it strangely felt like a quite good use case for a singleton.

Still some work to plan (implementing the other providers your lib offers, maybe PRing a Tumblr provider there), go ahead and submit some code if you want to :)

**Comment by dunglas** [comment]
Great! I'll update the readme to mention your extension.

**Comment by neemzy** [comment]
Thanks!
