### ISSUE TITLE
Unbound requirements should not be used

### ISSUE THREAD

**Issue by stof** [neemzy/share-extension#3]
See https://getcomposer.org/doc/faqs/why-are-unbound-version-constraints-a-bad-idea.md for the reasons.

`dev-master` is an unbound constraint, and it is also forbidding people to use stable versions of the library (meaning they cannot install your package without changing their minimum stability of adding their own requirement on the socialshare package to whitelist its dev version)

**Comment by neemzy** [comment]
Fixed by [26e4c17](https://github.com/neemzy/share-extension/commit/26e4c17ae391b43d59f81eea26ea099fa14faff4)
