### ISSUE TITLE
[Suggestion] support for abitrary providers

### ISSUE THREAD

**Issue by stof** [neemzy/share-extension#5]
Currently, the extension supports only some providers. this causes some issues:
- if you pass a SocialShare instance which does not contain the expected providers, the extension functions will break, while it is not explained anywhere
- if you pass a SocialShare instance with other providers (the scoop.it one for instance), it cannot be used.

the functions provided by the extension are also very generic names which could conflict.

The following API could be provided: exposing function named `share_url_google`, `share_url_facebook`, etc... for the sharing URL. The implementation would actually register `share_url_*` in Twig and the last part of the name would be the SocialShare provider name (allowing to support any provider).

Old function names would be kept for now but marking them as deprecated, and could be removed in a future version of the extension (Twig has a way to mark functions as deprecated now).

**Comment by neemzy** [comment]
That was a great suggestion :) I didn't bother with deprecating the current API as the extension is in its very early days. I took advantage of the API change to address the vulnerabilities you warned me about earlier.
